name: Update Profile Summary Cards

on:
  schedule:
    - cron: '0 0 * * *'  # Run every 24 hours at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-cards:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to access the README.md
      - name: Checkout repository
        uses: actions/checkout@v2

      # Get the list of repositories from the GitHub API
      - name: Get repositories activity
        id: get_repos
        run: |
          # Use GitHub API to get repositories for the current user (you can adjust the parameters if needed)
          curl -H "Authorization: token ${{ secrets.UPDATE_WEBSITE }}" \
            -s "https://api.github.com/users/${{ github.repository_owner }}/repos?per_page=100" | \
            jq '[.[] | {name: .name, pushed_at: .pushed_at}]'

      # Check if any repository has been updated in the last 24 hours
      - name: Check for recent activity
        id: check_activity
        run: |
          repos=$(echo "${{ steps.get_repos.outputs.repo_data }}" | jq -r '.[] | select(.pushed_at != null) | select(.pushed_at | fromdateiso8601 > (now - 86400)) | .name')
          
          if [[ -z "$repos" ]]; then
            echo "No recent activity found. Skipping update."
            echo "no_activity=true" >> $GITHUB_ENV
          else
            echo "Recent activity found in repositories: $repos"
            echo "no_activity=false" >> $GITHUB_ENV
          fi

      # Only update README.md if there was recent activity
      - name: Update README.md
        if: env.no_activity == 'false'
        run: |
          USERNAME="dvtsai"
          THEME="rose_pine"

          PROFILE_DETAILS="![dvtsai's card](http://github-profile-summary-cards.vercel.app/api/cards/profile-details?username=${USERNAME}&theme=${THEME})"
          REPOS_PER_LANGUAGE="![dvtsai's langrepo](http://github-profile-summary-cards.vercel.app/api/cards/repos-per-language?username=${USERNAME}&theme=${THEME})"
          MOST_COMMIT_LANGUAGE="![dvtsai's langcommit](http://github-profile-summary-cards.vercel.app/api/cards/most-commit-language?username=${USERNAME}&theme=${THEME})"
          STATS="![dvtsai's time](http://github-profile-summary-cards.vercel.app/api/cards/stats?username=${USERNAME}&theme=${THEME})"
          PRODUCTIVE_TIME="![dvtsai's smallcard](http://github-profile-summary-cards.vercel.app/api/cards/productive-time?username=${USERNAME}&theme=${THEME}&utcOffset=-5)"

          # Read the README.md and replace the old URLs with the new ones
          sed -i "s|http://github-profile-summary-cards.vercel.app/api/cards/profile-details?username=.*&theme=.*|${PROFILE_DETAILS}|" README.md
          sed -i "s|http://github-profile-summary-cards.vercel.app/api/cards/repos-per-language?username=.*&theme=.*|${REPOS_PER_LANGUAGE}|" README.md
          sed -i "s|http://github-profile-summary-cards.vercel.app/api/cards/most-commit-language?username=.*&theme=.*|${MOST_COMMIT_LANGUAGE}|" README.md
          sed -i "s|http://github-profile-summary-cards.vercel.app/api/cards/stats?username=.*&theme=.*|${STATS}|" README.md
          sed -i "s|http://github-profile-summary-cards.vercel.app/api/cards/productive-time?username=.*&theme=.*&utcOffset=.*|${PRODUCTIVE_TIME}|" README.md

      # Commit and push the updated README.md
      - name: Commit and push changes
        if: env.no_activity == 'false'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update profile summary cards"
          git push
